In [2]:
import numpy as np

a1 = np.array([1,2,3])

a1.ndim,a1.shape,type(a1),a1.dtype,a1.size

(1, (3,), numpy.ndarray, dtype('int64'), 3)

In [3]:
a2=np.array([[1,2,3],
             [4,5,6,]])
a2.ndim,a2.shape,type(a2),a2.dtype,a2.size

(2, (2, 3), numpy.ndarray, dtype('int64'), 6)

In [4]:
# a3 =  np.array([[[1,2,3],
#                  [4,5,6]]

#                 [[1,3,5],
#                  [4,2,3]]])


In [5]:
random_arr=np.random.randint(1,10,size=(5))
random_arr

array([8, 2, 2, 9, 3])

In [6]:
a='abc'
a[::-1]

'cba'

In [7]:
# import time

# start =time.time()
# arr=np.arrange(10000000)

#broadcasting,vektorization,

In [8]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
a2.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [10]:
a2.shape,a2.T.shape

((2, 3), (3, 2))

In [11]:
a2 @ a2.T

array([[14, 32],
       [32, 77]])

In [12]:
np.zeros(shape=[4,6])

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [13]:
np.ones(shape=[4,6])

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [14]:
np.sum(a2)

21

In [15]:
np.argmax(a2)

5

In [16]:
np.argmin(a2)

0

In [20]:
mat3 = np.random.randint(10, size=(4, 4))
mat4 = np.random.randint(10, size=(4, 3))

In [21]:
np.dot(mat3, mat4)

array([[ 38,  43,  41],
       [ 49, 104,  45],
       [ 46,  65,  43],
       [ 46, 101,  61]])

In [22]:
np.random.random((3, 5))

array([[0.78954748, 0.68426752, 0.64858114, 0.35470469, 0.5492531 ],
       [0.51799023, 0.18595737, 0.37152289, 0.50820594, 0.37523064],
       [0.96603947, 0.76573295, 0.92873073, 0.3769002 , 0.48896921]])